FROM node:20

ARG PORT
ENV VITE_PORT=$PORT

ARG AGENT_PEERS
ENV VITE_AGENT_PEERS=$AGENT_PEERS

RUN apt-get update && \
    apt-get install -y gnupg curl netcat-traditional systemctl iputils-ping && \
    curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
    gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg && \
    echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list && \
    apt-get update && \
    apt-get install -y mongodb-org && \
    rm -rf /var/lib/apt/lists/*
    # systemctl enable mongod && \
    # systemctl start mongod && \

WORKDIR /app

COPY . .

RUN npm install -g typescript
RUN npm install -g concurrently
RUN cd server && npm install && tsc


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]