# MONGO avec un shard de 3 noeuds
# 
# Auteur : P Mathieu
# Date   : 20/08/2021
#
# Pour le lancer
# docker-compose up -d

# Pour s'y connecter
# docker exec -it node1  mongosh --port 27018
# docker exec -it node2  mongosh --port 27018

# Pour arrêter
# docker-compose down -v


# ATTENTION, par defaut
# mongod , mongos servent sur 27017
# un shardsrv sert sur le port 27018
# un configSvr sert sur le port 27019

#---------------------------------------

services:
  # MongoDB nodes
  node1:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: node1
    hostname: node1
    command: /entrypoint.sh
    ports:
      - "27019:27018"
    volumes:
      - node1-data:/data/db
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    networks:
      v2_mongo-cluster:
        aliases:
          - node1


  node2:
    image: mongo:latest
    container_name: node2
    hostname: node2
    command: mongod --replSet shard1 --port 27018 --bind_ip_all
    ports:
      - "27020:27018"
    volumes:
      - node2-data:/data/db
    networks:
      v2_mongo-cluster:
        aliases:
          - node2

  node3:
    image: mongo:latest
    container_name: node3
    hostname: node3
    command: mongod --replSet shard1 --port 27018 --bind_ip_all
    ports:
      - "27021:27018"
    volumes:
      - node3-data:/data/db
    networks:
      v2_mongo-cluster:
        aliases:
          - node3


  # Exploration agents
  agent1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent1
    environment:
      - MONGO_URI=mongodb://node1:27018,node2:27018,node3:27018/v2grid?replicaSet=shard1
      - PORT=3001
      - AGENT_ID=agent1
      - AGENT_PEERS=http://agent2:3001,http://agent3:3001
    ports:
      - "3001:3001"
      - "8001:8000"
    networks:
     - v2_mongo-cluster
    depends_on:
      - node1
      - node2
      - node3

  agent2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent2
    environment:
      - MONGO_URI=mongodb://node1:27018,node2:27018,node3:27018/v2grid?replicaSet=shard1
      - PORT=3002
      - AGENT_ID=agent2
      - AGENT_PEERS=http://agent1:3001,http://agent3:3001
    ports:
      - "3002:3002"
      - "8002:8000"
    networks:
      - v2_mongo-cluster
    depends_on:
      - node1
      - node2
      - node3

  agent3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent3
    environment:
      - MONGO_URI=mongodb://node1:27018,node2:27018,node3:27018/v2grid?replicaSet=shard1
      - PORT=3003
      - AGENT_ID=agent3
      - AGENT_PEERS=http://agent1:3001,http://agent2:3001
    ports:
      - "3003:3003"
      - "8003:8000"
    networks:
      - v2_mongo-cluster
    depends_on:
      - node1
      - node2
      - node3

volumes:
  node1-data:
  node2-data:
  node3-data:

networks:
  v2_mongo-cluster:
    driver: bridge