# Stage 1: CouchDB
FROM docker.io/apache/couchdb:3.3.2 AS couchdb

# Stage 2: Node.js
FROM node:20

# Set the Erlang magic cookie
ENV COUCHDB_ERL_COOKIE="8zplQ4cMBYma4y6"

# Copy CouchDB binaries and dependencies from the first stage
COPY --from=couchdb /opt/couchdb /opt/couchdb
COPY --from=couchdb /etc/couchdb /etc/couchdb
COPY --from=couchdb /usr/lib /usr/lib
COPY --from=couchdb /usr/bin /usr/bin
COPY --from=couchdb /opt/couchdb/data /opt/couchdb/data
COPY --from=couchdb /opt/couchdb/var/log /opt/couchdb/var/log

WORKDIR /app
COPY . .

# Install Node.js dependencies
RUN apt update && apt install -y curl gnupg apt-transport-https procps && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt install -y nodejs && \
    wget http://ftp.de.debian.org/debian/pool/main/p/procps/libprocps8_3.3.17-5_amd64.deb && \
    dpkg -i libprocps8_3.3.17-5_amd64.deb && \
    npm install -g typescript concurrently && \
    npm install && cd server && npm install && tsc && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]